name: 'Wait'
description: 'Wait a designated number of milliseconds'
inputs:
  repo-token:
    description: 'GitHub repository token'
    required: true
  webhook-id: 
    description: 'Discord webhook id'
    required: true
  webhook-token: 
    description: 'Discord webhook token'
    required: true
outputs:
  time: # output will be available to future steps
    description: 'The message to output'
runs:
  using: 'node12'
  main: 'dist/index.js'
